# Configure Firebase shared visitor chat (chat-config.js)
$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
$RulesPath = Join-Path $Root 'firebase\database.rules.json'
$ConfigPath = Join-Path $Root 'chat-config.js'

Write-Host ''
Write-Host '=== Firebase Shared Visitor Chat Setup ===' -ForegroundColor Cyan
Write-Host ''
Write-Host '1. Open https://console.firebase.google.com/'
Write-Host '2. Create Realtime Database (Build > Realtime Database)'
Write-Host '3. Paste rules from:' $RulesPath
Write-Host '4. Project Settings > Your apps > Web app > copy firebaseConfig'
Write-Host ''
Start-Process 'https://console.firebase.google.com/'

$apiKey = Read-Host 'apiKey'
$authDomain = Read-Host 'authDomain'
$databaseURL = Read-Host 'databaseURL'
$projectId = Read-Host 'projectId'

if (-not $apiKey -or -not $databaseURL -or -not $projectId) {
    Write-Host 'apiKey, databaseURL, projectId are required.' -ForegroundColor Red
    exit 1
}

if (-not $authDomain) {
    $authDomain = "$projectId.firebaseapp.com"
}

$content = @"
/** Visitor chat storage — Firebase shared mode (generated by setup-firebase-chat.ps1) */
export const CHAT_CONFIG = {
  storage: 'firebase',
  maxMessages: 300,
  firebase: {
    apiKey: '$apiKey',
    authDomain: '$authDomain',
    databaseURL: '$databaseURL',
    projectId: '$projectId',
  },
};
"@

Set-Content -Path $ConfigPath -Value $content -Encoding UTF8
Write-Host ''
Write-Host "Updated: $ConfigPath" -ForegroundColor Green
Write-Host 'Next: git add chat-config.js && git commit && git push' -ForegroundColor Yellow
Write-Host ''